# Generated by Django 5.1.4 on 2024-12-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_description', models.TextField(verbose_name='Description of event: ')),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_address', models.TextField()),
                ('event_capacity', models.IntegerField()),
                ('event_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('event_uuid', models.UUIDField()),
            ],
        ),
    ]
