# Generated by Django 5.1.4 on 2024-12-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0004_rename_event_ticket_event_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
