# Generated by Django 5.1.4 on 2024-12-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0005_ticket_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('General', 'General'), ('Fanpit', 'Fanpit'), ('VIP', 'Vip')], default='General', max_length=7),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
