# Generated by Django 4.2.17 on 2025-01-01 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0008_ticket_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_purchase_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
