# Generated by Django 4.2.17 on 2025-01-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0009_ticket_ticket_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='original_event_capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
