# Generated by Django 4.2.17 on 2025-01-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0011_rename_original_event_capacity_event_original_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='original_capacity',
        ),
    ]
