# Generated by Django 4.2.17 on 2025-01-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0012_remove_event_original_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(default='Khalti'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('General', 'General'), ('Fanpit', 'Fanpit'), ('VIP', 'Vip')], default='General', max_length=10),
        ),
    ]
