# Generated by Django 4.2.17 on 2025-01-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0013_ticket_payment_completed_ticket_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('On Venue', 'On Venue'), ('Khalti', 'Khalti')], default='Khalti'),
        ),
    ]
