# Generated by Django 4.2.17 on 2025-01-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0016_alter_ticket_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='payment_method',
        ),
    ]
